# Generated by Django 2.2 on 2021-05-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultanttime',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
